// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGBJVxAM5xv4KBNHrPYiJ1mBTX4iVWwuY',
    appId: '1:551668721641:web:4340771f288b5d9f660d78',
    messagingSenderId: '551668721641',
    projectId: 'polytech-rdp',
    authDomain: 'polytech-rdp.firebaseapp.com',
    storageBucket: 'polytech-rdp.appspot.com',
    measurementId: 'G-PGYHEES3B5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3gYFdjcc6sJXAnLoabaNGytIJwFdg-Cg',
    appId: '1:551668721641:android:523f42cce6bac322660d78',
    messagingSenderId: '551668721641',
    projectId: 'polytech-rdp',
    storageBucket: 'polytech-rdp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs8_4sf93dtdtDGTCZaZxIuVMmNCUZB00',
    appId: '1:551668721641:ios:b4eee65b4764767e660d78',
    messagingSenderId: '551668721641',
    projectId: 'polytech-rdp',
    storageBucket: 'polytech-rdp.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs8_4sf93dtdtDGTCZaZxIuVMmNCUZB00',
    appId: '1:551668721641:ios:b4eee65b4764767e660d78',
    messagingSenderId: '551668721641',
    projectId: 'polytech-rdp',
    storageBucket: 'polytech-rdp.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGBJVxAM5xv4KBNHrPYiJ1mBTX4iVWwuY',
    appId: '1:551668721641:web:958edfbf302b3d52660d78',
    messagingSenderId: '551668721641',
    projectId: 'polytech-rdp',
    authDomain: 'polytech-rdp.firebaseapp.com',
    storageBucket: 'polytech-rdp.appspot.com',
    measurementId: 'G-N2Y4Z9K52X',
  );

}