// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ_h11gGKDu8c_UkNdmSKeFj7Jx6jcLbY',
    appId: '1:855204407087:web:a84d94276a70a4c7c5a3da',
    messagingSenderId: '855204407087',
    projectId: 'rdp-todolist-584c1',
    authDomain: 'rdp-todolist-584c1.firebaseapp.com',
    storageBucket: 'rdp-todolist-584c1.appspot.com',
    measurementId: 'G-F9X1NWJK78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMVouSNgn9xZNpLf6vFIdxgqFEXhO5aPY',
    appId: '1:855204407087:android:1e76f240764f99bfc5a3da',
    messagingSenderId: '855204407087',
    projectId: 'rdp-todolist-584c1',
    storageBucket: 'rdp-todolist-584c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpuyLyUxUKS36yTOM_OMwFk7eSjw_7L-Y',
    appId: '1:855204407087:ios:eea5b3e056f2c8dac5a3da',
    messagingSenderId: '855204407087',
    projectId: 'rdp-todolist-584c1',
    storageBucket: 'rdp-todolist-584c1.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpuyLyUxUKS36yTOM_OMwFk7eSjw_7L-Y',
    appId: '1:855204407087:ios:eea5b3e056f2c8dac5a3da',
    messagingSenderId: '855204407087',
    projectId: 'rdp-todolist-584c1',
    storageBucket: 'rdp-todolist-584c1.appspot.com',
    iosBundleId: 'com.example.rdpTodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ_h11gGKDu8c_UkNdmSKeFj7Jx6jcLbY',
    appId: '1:855204407087:web:037bfcb9a5b3b5e2c5a3da',
    messagingSenderId: '855204407087',
    projectId: 'rdp-todolist-584c1',
    authDomain: 'rdp-todolist-584c1.firebaseapp.com',
    storageBucket: 'rdp-todolist-584c1.appspot.com',
    measurementId: 'G-786BPB0S8D',
  );
}
